sudo: false

language: node_js

node_js:
  - 6

before_script:
  - npm install -g gulp bower coveralls
  - npm install
  - bower install

script:
  - gulp tests
  - cat ./coverage/lcov.info | coveralls
  - gulp release

